### ISSUE TITLE
Link to JobSphere in README

### ISSUE THREAD

**Issue by SreenikethanI** [acmbpdc/JobSphere#1]
**Bug description**
Link to the JobSphere page in README.md should be prefixed with https:// or something, since it currently assumes it's a relative path in the repo.

**Location of error:**
https://github.com/acmbpdc/JobSphere/commit/2bf3343c21bf323fff0b170eac8a2e77245a0a28#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R5

**Comment by Fir121** [comment]
Nice catch! Thanks for pointing that out
